name: FastAPI Churn Project CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run ML training script
      - name: Train ML Model
        run: python train_model.py

      # 5️⃣ Run tests (optional)
      # - name: Run tests
      #   run: pytest tests/

      # 6️⃣ Lint / code quality (optional)
      # - name: Lint code
      #   run: flake8 app/

      # 7️⃣ Build Docker image (optional)
      # - name: Build Docker image
      #   run: docker build -t churn-api .

      # 8️⃣ Deploy (optional)
      # Add deployment steps here (e.g., AWS, Render, Heroku)
